_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
import numpy as np
a = np.array([10, 5, 7, 20, 15, -9, 33])
print(a)
print('Maximum value:', np.max(a))
print('Minimum value:', np.min(a))

[10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [2]:
a = np.array([10, 5, 7, 20, 15, -9, 33])
a.sort()
print('Maximum value:', a[-1])

Maximum value: 33


___
**Write a program to accept two matrices [[1,2],[3,4]], [[5,6],[7,8]]and find their sum**
___

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)

[[ 6  8]
 [10 12]]


___
**Write a program to accept a 3 X 3 matrix and find the transpose of the same**
___

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


____
**Write a program to take a 4 X 4 matrix as input from the user and find the sum of all the elements of the matrix**
____

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(np.sum(a))

136


___
**Write a program to take a 5 X 5 matrix from the user and find the sum of each column of the matrix**
___

In [6]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(np.sum(a, axis=0))

[55 60 65 70 75]


____
**Write a program to take a 6 X 6 matrix from the user and find the sum of each row of the matrix**
____

In [7]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])
print(np.sum(a, axis=1))

[ 21  57  93 129 165 201]


___
**Write a program to initialize a 4 X 5 matrix, with random integers and then compute the sine of each element in the matrix and print it**

In [8]:
a = np.random.randint(1, 10, size=(4,5))
print(np.sin(a))

[[-0.7568025   0.41211849  0.90929743 -0.7568025   0.14112001]
 [ 0.84147098  0.84147098  0.41211849  0.14112001 -0.7568025 ]
 [-0.2794155   0.84147098  0.14112001  0.14112001  0.98935825]
 [-0.2794155  -0.95892427  0.6569866  -0.2794155   0.90929743]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [9]:
a = np.random.rand(5,6)
print(a[2:4, 1:4])

[[0.77227481 0.24808034 0.56254528]
 [0.15145108 0.54367242 0.49459102]]


### Great Job!